Add boot animation
R0merol/Number-Game-v0.1 pull request #35
Opened 2022-10-01 16:17 UTC by sparshg

Added boot animation with configurable wait times between each line.

2022-10-01 18:26 UTC, R0merol requested changes
Let players skip the boot screen

2022-10-01 18:26 UTC, R0merol commented on code/main.py
> +            if boot_menu.boot_text.anim_completed and (event.type == pygame.KEYDOWN or event.type == pygame.MOUSEBUTTONDOWN):
Players should have the ability to just skip the booting. After all, it's just like an intro cutscene. So you should leave this part of the code alone.

2022-10-01 18:38 UTC, R0merol commented
I was thinking if you could [add this](https://github.com/R0merol/Number-Game-v0.1/issues/20#issuecomment-1264448231) as well, I hope I'm not asking too much from you

2022-10-02 05:29 UTC, sparshg commented
Added loading animation

2022-10-02 08:25 UTC, R0merol approved these changes
It's looking awesome! Thank you so much for this!

2022-10-02 08:25 UTC, merged